subquery:
  node:
    image: gcr.io/fetch-ai-sandbox/subquery-node
    tag: 239fe08
    startBlock: "827201"
    networkEndpoint: https://rpc-dorado.fetch.ai:443
    chainId: "dorado-1"

  api:
    image: gcr.io/fetch-ai-sandbox/subquery-api
    tag: v1.4.0

    replicas: 1

    dns:
      # Gateways
      ingressGateway: "istio-fetch-gaia-ig"

      # DNS Settings
      name: staging.subquery.sandbox-london-b.fetch-ai.com
      target: "gaia.sandbox-london-b.fetch-ai.com"
      additionalDnsNames: []

db:
  image: postgres
  tag: 14-alpine

  name: subquery
  user: subquery
  gcpProject: fetch-ai-sandbox
  gcpSecret: sandbox_subquery_postgres

  storageSize: 7Gi
