name: Docker build latest

on:
  pull_request:
    branches: [main]

jobs:
  ledger-subquery:
    name: build
    runs-on: ubuntu-latest

    env:
      IMAGE_PROJECT_ID: fetch-ai-images
      NODE_IMAGE_NAME: subquery-node
      API_IMAGE_NAME: subquery-api

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Get image tag
        id: vars
        shell: bash
        run: |
          echo "::set-output name=tag_name::latest"

      # Authenticate to GCP
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.DEVOPS_IMAGES_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - run: 'gcloud info'

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: Configure Docker
        run: |
          gcloud auth configure-docker -q

      # Docker build ; docker push
      - name: Build and push subquery node
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/node.dockerfile
          push: true
          tags: |
            gcr.io/${{ env.IMAGE_PROJECT_ID }}/${{ env.NODE_IMAGE_NAME }}:${{ steps.vars.outputs.tag_name }}

      - name: Build and push graphql api
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/api.dockerfile
          push: true
          tags: |
            gcr.io/${{ env.IMAGE_PROJECT_ID }}/${{ env.API_IMAGE_NAME }}:${{ steps.vars.outputs.tag_name }}
