name: End-to-end tests

on:
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update
        run: sudo apt update
      - name: Install OS dependencies
        run: sudo apt install -y python3-dev nodejs

      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install linter dependencies
        run: yarn install

      - name: Lint TypeScript
        run: yarn lint

      - name: Start-up local test environment
        uses: isbang/compose-action@v1.2.0
        with:
          compose-file: "./ci-compose.yml"

      # NB: doing this here gives the test env time to come up
      - name: Install test dependencies
        uses: palewire/install-python-pipenv-pipfile@v2
        with:
          python-version: 3.9

      - name: Run unit tests
        run: pipenv run python -m unittest discover -s ./tests/unit

      - name: Run end-to-end tests
        run: pipenv run python -m unittest discover -s ./tests/e2e
